config/routes.rb
Rails.application.routes.draw do
  root 'properties#index'
  resources :properties do
    post 'create_contact', on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/properties_controller.rb
require 'httparty'

class PropertiesController < ApplicationController
  before_action :set_client

  def index
    @results = @client.properties.search(limit: 15, search: { statuses: [:published] })
    (params[:page].to_i - 1).times.collect { @results.next_page } if params[:page]
    @properties = @results.response.content
  end

  def show
    @property = @client.properties.find(params[:id])
  end

  def create_contact
    contact_options = {
      headers: {
        'Content-Type' => 'application/json',
        'X-Authorization' => ENV['API_KEY']
      },
      body: define_body(params).to_json
    }

    @response = HTTParty.post('https://api.stagingeb.com/v1/contact_requests', contact_options)

    redirect_to property_path(params[:id]), notice: "Contact created, status: #{@response.parsed_response['status']}"
  end

  private

  def set_client
    @client = EasyBroker.client
  end

  def define_body(params)
    {
      name: params[:name],
      phone: params[:phone],
      email: params[:email],
      property_id: params[:id],
      message: params[:message],
      source: params[:source]
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pagination_helper.rb
module PaginationHelper
  def total_pages(data)
    data.total / 15
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasybrokerTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1 class="title">
      <%= link_to 'EasyBroker', root_path %>
      </h1>
    </header>
    <%= yield %>
  </body>
</html>

app/views/properties/_property.html.erb
<div class="properties-card">
  <div>
    <%= property.public_id %>
  </div>

  <div>
    <%= property.title %>
  </div>

  <div class="properties-image">
    <% if property.title_image_thumb%>
      <%= image_tag property.title_image_thumb%>
    <% else %>
      <%= image_tag("default.jpg", width: 200)%>
    <% end %>
  </div>

  <div>
    <%= property.property_type%>
  </div>

  <div>
    <%= property.location%>
  </div>

  <%= link_to '', property_path(property.public_id), class: "properties-link" %>
</div>

app/views/properties/index.html.erb
<section class="container">
  <div class="properties-container">
    <%= render partial: "property", collection: @properties%>
  </div>
  <% page_number = 1 %>
  <div class="pagination-container">
    <% until  page_number > total_pages(@results) do %>
      <%= link_to page_number, properties_path(:page => page_number) %>
      <% page_number+=1 %>
    <% end %>
  </div>
</section>

app/views/properties/show.html.erb
<div class="property-container">
  <div class="property-card">
    <h1 class="property-title">
      <%= @property.title%>
    </h1>
    <h2>Public ID</h2>
    <p>
      <%= @property.public_id%>
    </p>

    <h2>Description</h2>
    <p>
      <%= @property.description%>
    </p>

    <% if !@property.property_images.empty? %>
      <div class="slideshow-container">
        <% @property.property_images.each_with_index do |image, i| %>
          <div class="mySlides fade">
            <div class="numbertext"> <%= i + 1 %> / <%= @property.property_images.size %> </div>
            <%= image_tag image.url %>
          </div>
        <% end %>

        <a class="prev">&#10094;</a>
        <a class="next">&#10095;</a>
      </div>
    <% else %>
      <%= image_tag("default.jpg", width: 672)%>
    <% end %>
    
    <h2>Property Type</h2>
    <p>
      <%= @property.property_type%>
    </p>

    <h2>Location</h2>
    <p>
      <%= @property.location.name %>
    </p>
  </div>

  <div class="form-area">
    <h1>Create a Contact </h1>
    <% flash.each do |type, msg| %>
      <div class="form-response">
        <%= msg %>
      </div>
    <% end %>
    <%= form_with url: create_contact_property_path, class: "contact-form" do |form| %>
      <div class="form-input">
        <%= form.label :name, class: "label"%>
        <%= form.text_field :name, placeholder: "Write your name...", class: "input", :required => true %>
      </div>
      <div class="form-input">
        <%= form.label :phone, class: "label"%>
        <%= form.text_field :phone, placeholder: "5559090909", class: "input", :required => true %>
      </div>
      <div class="form-input">
        <%= form.label :email, class: "label"%>
        <%= form.email_field :email, placeholder: "Write your email...", class: "input", :required => true %>
      </div>
      <div class="form-input">
        <%= form.label :message, class: "label"%>
        <%= form.text_area :message, placeholder: "Write a message...", class: "input", :required => true %>
      </div>
      <div class="form-input">
        <%= form.label :source, class: "label"%>
        <%= form.text_field :source, placeholder: "Write contact page...", class: "input", :required => true %>
      </div>

      <%= form.submit class: "submit" %>
    <% end %>
  </div>
</div>

<% if !@property.property_images.empty? %>
  <%= javascript_pack_tag "slideshow" %>
<% end %>